const toggleParagraph = document.getElementById('toggleParagraph');
const button1 = document.getElementById('button1');
const button2 = document.getElementById('button2');

button1.addEventListener('click', () => {
    toggleParagraph.textContent = "Oasis adalah band rock asal Inggris yang dibentuk di Manchester pada tahun 1991. Pada awalnya menggunakan nama the Rain, grup ini dibentuk oleh Liam Gallagher (vokal), Paul Arthurs (gitar), Paul McGuigan (bass), dan Tony McCarroll (drum dan perkusi), hingga kemudian ikut bergabung pula kakak Liam, Noel Gallagher (gitar dan vokal). Setelah mengganti nama menjadi Oasis, para anggotanya menandatangani kontrak dengan label rekaman indie Creation Records dan setelah itu merilis album perdana mereka Definitely Maybe pada tahun 1994. Tahun berikutnya, Oasis merilis (What's the Story) Morning Glory? bersama drummer baru Alan White di tengah persaingan dengan band britpop lain, Blur. Gallagher bersaudara juga secara berkala menjadi topik dalam tabloid dan berita atas gaya hidup liar dan perselisihan mereka. Pada tahun 1997, Oasis merilis album ketiga mereka, Be Here Now. Walaupun album memiliki angka penjualan tercepat dalam sejarah Inggris, popularitas album ketiga mereka menurun dengan sangat cepat. Oasis kemudian kehilangan anggota Paul McGuigan dan Paul Arthurs ketika mereka dalam proses rekaman dan akan merilis Standing on the Shoulder of Giants pada tahun 2000. Dua posisi kosong tersebut kemudian digantikan oleh Gem Archer dan Andy Bell. Oasis berhasil menemukan kesuksesan dan popularitas kembali melalui album Don't Believe the Truth pada tahun 2005. Pada Agustus 2009, Noel Gallagher mengumumkan pengunduran dirinya dari Oasis pasca perkelahian belakang panggung dengan Liam. Anggota tersisa dari Oasis, dipimpin oleh Liam Gallagher, memutuskan untuk melanjutkan pekerjaan mereka bersama di bawah nama Beady Eye, sementara Noel membentuk proyek solo Noel Gallagher's High Flying Birds.";
});

button2.addEventListener('click', () => {
    toggleParagraph.textContent = "Oasis, dengan tujuh singel dan tujuh album yang pernah memuncaki posisi satu di tangga musik Inggris, pernah memenangkan lima belas NME Awards, sembilan Q Awards, empat MTV Europe Music Awards dan enam Brit Awards, termasuk salah satunya pada tahun 2007 untuk kontribusi luar biasa terhadap musik dan satu untuk album terbaik dalam 30 tahun terakhir berdasarkan polling pendengar BBC Radio 2. Oasis juga pernah dinominasikan untuk tiga buah Grammy Award. Terhitung per tahun 2009, Oasis telah menjual sekitar 70 juta copy rekaman mereka di seluruh dunia. Juga Oasis didaftar dalam Guinness Book of World Records pada tahun 2010 untuk “Longest Top 10 UK Chart Run By A Group” setelah berhasil memposisikan 22 single hits di top-10 chart musik Inggris. Oasis juga memegang rekor dunia Guinness sebagai entitas musik tersukses antara tahun 1995 hingga 2005, menduduki selama 765 minggu di chart musik Top 75";
});